SELECT * FROM historial;
 INSERT INTO historial(texto) values('ls'); 
 INSERT INTO historial(texto) values('pwd'); 
 INSERT INTO historial(texto) values('cd ..'); 
 INSERT INTO historial(texto) values('cd home/'); 
 INSERT INTO historial(texto) values('cd codigo/'); 
 INSERT INTO historial(texto) values('ls'); 
 INSERT INTO historial(texto) values('ls -ls'); 
 INSERT INTO historial(texto) values('vim ejercicio2.sh'); 
 INSERT INTO historial(texto) values('pwd'); 
 INSERT INTO historial(texto) values('cd ..'); 
 INSERT INTO historial(texto) values('cd ./home/codigo/'); 
 INSERT INTO historial(texto) values('pwd'); 
 INSERT INTO historial(texto) values('ls'); 
 INSERT INTO historial(texto) values('vim ejercicio2V2.sh'); 
 INSERT INTO historial(texto) values('chmod +x ./ejercicio2V2.sh'); 
 INSERT INTO historial(texto) values('./ejercicio2V2.sh'); 
